version: '3'

services:
  db:
    image: postgres
    container_name: maps-postgres
    environment:
      POSTGRES_PASSWORD: q1w2
    networks:
      - backend_network
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "postgres" ]
      interval: 5s
      timeout: 5s
      retries: 3

  backend:
    build:
      context: ./
    image: maps-backend
    container_name: maps-backend
    networks:
      - backend_network
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy

networks:
  backend_network:
    name: backend_network