version: '3'

services:
  db:
    image: postgres
    container_name: maps-postgres
    environment:
      POSTGRES_PASSWORD: q1w2
    networks:
      - maps_network
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "postgres" ]
      interval: 5s
      timeout: 5s
      retries: 3

  backend:
    build:
      context: ./backend
    image: maps-backend
    container_name: maps-backend
    networks:
      - maps_network
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-prod
    image: maps-frontend
    container_name: maps-frontend
    networks:
      - maps_network
    depends_on:
      backend:
        condition: service_started

  nginx:
    image: nginx:alpine
    container_name: maps-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - maps_network
    depends_on:
      frontend:
        condition: service_started

networks:
  maps_network:
    driver: bridge
